Update to work with LTS-12.x and Servant 0.14
haskell-servant/servant-ekg pull request #8
Opened 2019-02-11 20:02 UTC by jessekempf

2019-02-11 21:15 UTC, phadej requested changes
I don't accept bound removals.

2019-02-11 21:15 UTC, phadej commented on servant-ekg.cabal
> -    , ekg-core              >=0.1.1.6  && <0.2
:-1:

2019-02-11 22:31 UTC, alpmestan requested changes
Yeah we want accurate bounds, this is not a stack-only package (if that's even a thing), we do want it to work flawlessly for cabal-install users, which requires proper version bounds. Thanks!

2019-02-11 22:36 UTC, jessekempf commented
@phadej, @alpmestan: Bounds are back.

2019-02-12 19:40 UTC, jessekempf commented
@phadej, @alpmestan: How does the current changeset look?

2019-02-28 07:07 UTC, phadej commented
Superseded by #11

2019-02-28 07:07 UTC, closed without merging